services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8000:5432"

  fastapi:
    build: ./app
    ports:
      - "9000:80"
    volumes:
      - ./app:/code
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres

  frontend:
    build: ./ui
    ports:
      - "5000:3000"
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
    environment:
      - NODE_ENV=development
    command: npm start
    depends_on:
      - fastapi

volumes:
  postgres_data:
